// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {youtube} from '../models';
import {video} from '../models';

export function CheckFFmpeg():Promise<boolean>;

export function ExportClip(arg1:main.ExportOptions):Promise<void>;

export function GetVideoInfo(arg1:string):Promise<youtube.VideoInfo>;

export function GetVideoServer():Promise<video.Server>;

export function InstallFFmpeg():Promise<void>;

export function LoadVideo(arg1:string):Promise<main.VideoInfo>;

export function SelectOutputDirectory():Promise<string>;
