// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelLoad():Promise<void>;

export function CheckToolchain():Promise<boolean>;

export function ExportClip(arg1:main.ExportOptions):Promise<void>;

export function GetDiagnostics():Promise<string>;

export function LoadVideo(arg1:string):Promise<main.VideoInfo>;

export function SelectOutputDirectory():Promise<string>;
