// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelLoad() {
  return window['go']['main']['App']['CancelLoad']();
}

export function CheckToolchain() {
  return window['go']['main']['App']['CheckToolchain']();
}

export function ExportClip(arg1) {
  return window['go']['main']['App']['ExportClip'](arg1);
}

export function GetDiagnostics() {
  return window['go']['main']['App']['GetDiagnostics']();
}

export function LoadVideo(arg1) {
  return window['go']['main']['App']['LoadVideo'](arg1);
}

export function SelectOutputDirectory() {
  return window['go']['main']['App']['SelectOutputDirectory']();
}
