// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckFFmpeg() {
  return window['go']['main']['App']['CheckFFmpeg']();
}

export function ExportClip(arg1) {
  return window['go']['main']['App']['ExportClip'](arg1);
}

export function GetVideoInfo(arg1) {
  return window['go']['main']['App']['GetVideoInfo'](arg1);
}

export function GetVideoServer() {
  return window['go']['main']['App']['GetVideoServer']();
}

export function InstallFFmpeg() {
  return window['go']['main']['App']['InstallFFmpeg']();
}

export function LoadVideo(arg1) {
  return window['go']['main']['App']['LoadVideo'](arg1);
}

export function SelectOutputDirectory() {
  return window['go']['main']['App']['SelectOutputDirectory']();
}
